### ISSUE TITLE
two alerts for one tests state is not persisting 

### ISSUE THREAD

**Issue by Sraza11** [thousandeyes/terraform-provider-thousandeyes#111]
I have two alerts attached to a test.  Even after the "terraform apply" if I run terraform plan it shows pending change. 
@tduzan-te @sfreitas-te @pedro-te 

``` 
# thousandeyes_agent_to_server.XXXXXX will be updated in-place
  ~ resource "thousandeyes_agent_to_server" "XXXXX" {
        id                     = "XXXXX"
      ~ path_trace_mode        = "classic" -> "inSession"
        # (24 unchanged attributes hidden)

      + alert_rules {
          + rule_id = 448261
        }

        # (6 unchanged blocks hidden)
    }

Plan: 0 to add, 14 to change, 0 to destroy.
```

**Comment by pedro-te** [comment]
Hi @Sraza11 ,

Thanks for reporting this. 
May I ask you to share a snippet of your terraform code that leads to this?
Additionally is the plan showing changes to `path_trace_mode` and `alert_rules` on every run? Are those the pending changes that you're referring to? Please try to add as many details as possible so that we may attempt to reproduce the issue and resolve it.

Thanks,
Pedro

**Comment by Sraza11** [comment]
the following snippet of terraform code that is triggering this behavior.  if I remove the second alert rule (rule_id=448261) the issue goes away. 

```tf
alert_rules {
    rule_id = 448261
  }
```
this plan is not showing changes to path_trace_mode but just the _**Alert rule**_.  here is what it offers the difference it will apply with terraform apply. 



```tf
~ resource "thousandeyes_agent_to_server" "subnet-136-1" {
        id                     = "3168076"
        # (25 unchanged attributes hidden)

      + alert_rules {
          + rule_id = 448261
        }

        # (6 unchanged blocks hidden)
    }
```

**Comment by pedro-te** [comment]
@Sraza11 can you share the full resource with us, please? I want to try to reproduce the issue.

**Comment by joaomper-TE** [comment]
@Sraza11 while debugging this I found out that this only happens if one of the Alert Rules is a "default" one. Still not sure why, but just letting you know in case you need unblocking for this.

![image](https://github.com/thousandeyes/terraform-provider-thousandeyes/assets/85952626/f17e3c2e-e45d-4792-9606-be970a7bd220)
