### ISSUE TITLE
Thousandeyes Cloud Agents IP addresses

### ISSUE THREAD

**Issue by abdulbello5** [thousandeyes/terraform-provider-thousandeyes#128]
Looking at the Thousandeyes terraform documentation, there doesn't seem to a datasource available to pull cloud agent IP addresses. i.e We need to pull in the IP addresses of agent in Sao-paulo Brazil for example and then allow those IP's on our network firewall. so, something like the terraform code below to retreive the IP's:

data "te_agent_ip" "test" {
 id  = "agent_name"
value  =  [<IP addresses>]
}

Can this be provided?

**Comment by aggallim** [comment]
We need this too...... +1

**Comment by AJD-UK** [comment]
The TE equivalent of https://ip-ranges.amazonaws.com/ip-ranges.json would really help here

**Comment by sfreitas-te** [comment]
Currently we have this tool to obtain this information https://github.com/thousandeyes/te-iplist

**Comment by AJD-UK** [comment]
> Currently we have this tool to obtain this information https://github.com/thousandeyes/te-iplist

Thanks @sfreitas-te Any way to raise feature requests to add explicit proxy support to the tool?  Add an issue on GitHub?

**Comment by joaomper-TE** [comment]
Hey @AJD-UK ! We created an internal issue in our side to add this feature. We will keep you updated

**Comment by joaomper-TE** [comment]
@AJD-UK @abdulbello5 @aggallim instead of adding a new datasource, this [PR](https://github.com/thousandeyes/terraform-provider-thousandeyes/pull/150) uses the existing `thousandeyes_agent` datasource and adds a new output for the IP Address list. Is this okay for your use-cases?

**Comment by joaomper-TE** [comment]
Hey @AJD-UK and thanks for the detailed answer. Regarding point 1, it looks like this [PR](https://github.com/thousandeyes/terraform-provider-thousandeyes/pull/150) won't cut it and that you actually need the `public IP Addresses` and not the `ipAddresses` correct?

And since our `/agents` endpoint only returns the `publicIpAddresses` for Enterprise agents - not `Cloud` agents - this would require new development to the endpoint prior to actually having a Terraform Data source within this repo using that info.

Let me know if my assumptions are correct.

Thanks

**Comment by joaomper-TE** [comment]
Hey @AJD-UK , and sorry for the misunderstanding. The PR aforementioned will actually cut it for you, since it will output the IP Addresses for the cloud agents, which are the public ones.

In the future we may go even further and output the public IPs for Enterprise Agents, but for now I'll go ahead and merge the PR and close this issue if that's ok.

**Comment by joaomper-TE** [comment]
https://github.com/thousandeyes/terraform-provider-thousandeyes/pull/150 merged and you can test the new datasource using v2.0.5
